on:
  pull_request:
    branches:
      - develop
    types: [closed]

jobs:
  add_label:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.github_token }}
          labels: |
            next-release
