name: cd

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Create release
        run: |
          gh pr list --state merged --label "next release" --json title,number --jq '.[] | .result = "- " + .title + " #" + (.number|tostring) | .result' > next-release.md
          gh release create ${{ github.ref }} -F next-release.md ${{ (contains(github.ref, '-') && '--prerelease') || '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
