on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  add_label:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2
      - name: remove labels
        run: gh pr list --state merged --label "next release" --json number --jq .[].number | awk '{ system("gh pr edit "$1" --remove-label \"next release\"") }'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
